# Generated by Django 4.2.1 on 2023-06-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("sub_categories", models.ManyToManyField(to="web.category")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("price", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=0)),
                ("depth", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("description", models.TextField(default="")),
                ("slug", models.SlugField(blank=True, default="")),
                ("category", models.ManyToManyField(to="web.category")),
            ],
        ),
    ]
