# Generated by Django 4.2.1 on 2023-06-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_remove_product_category_alter_product_sub_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
    ]
