# Generated by Django 4.2.1 on 2023-06-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="depth",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="height",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
