# Generated by Django 4.2.1 on 2023-06-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_alter_product_depth_alter_product_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="depth",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="product",
            name="height",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
