# Generated by Django 4.2.1 on 2023-06-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_alter_product_depth_alter_product_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="images"),
        ),
        migrations.AddField(
            model_name="product",
            name="image1",
            field=models.ImageField(blank=True, default="", upload_to="images"),
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(blank=True, default="", upload_to="images"),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(blank=True, default="", upload_to="images"),
        ),
        migrations.AddField(
            model_name="product",
            name="image4",
            field=models.ImageField(blank=True, default="", upload_to="images"),
        ),
    ]
