# Generated by Django 4.2.1 on 2023-06-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_product_image_product_image1_product_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shipping_price",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_time",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
