# Generated by Django 4.2.1 on 2023-06-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(default="", max_length=100)),
                ("phoneNum", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("bTime", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
