# Generated by Django 4.2.1 on 2023-06-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="email",
            new_name="bemail",
        ),
        migrations.RemoveField(
            model_name="message",
            name="content",
        ),
        migrations.RemoveField(
            model_name="message",
            name="name",
        ),
        migrations.RemoveField(
            model_name="message",
            name="phoneNum",
        ),
        migrations.AddField(
            model_name="message",
            name="bcontent",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="message",
            name="bname",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="message",
            name="bphoneNum",
            field=models.CharField(default="", max_length=20),
        ),
    ]
